[workspace]
members = [
    "arm7app",
    "arm7rt",
    "arm9app",
    "arm9rt"
]

[profile.release]
opt-level = 3
lto = true
panic = "abort"
incremental = false
codegen-units = 1

[profile.dev]
opt-level = 3
lto = true
panic = "abort"
incremental = false
codegen-units = 1
