[package]
name = "arm7app"
version = "0.1.0"
authors = ["pedrosf"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arm7rt = { path = "../arm7rt" }