[build]
target = "armv4t-none-eabi"
[target.armv4t-none-eabi]
rustflags = ["-C", "link-arg=-Tlink4.ld"]
[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]