[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
[build]
target = "armv5te-none-eabi"
[target.armv5te-none-eabi]
rustflags = ["-C", "link-arg=-Tlink5.ld"]
